export const PATRON = {
    PATRON_GET_LIST: "PATRON/GET_LIST",
    PATRON_GET_LIST_SUCCESS: "PATRON/GET_LIST_SUCCESS",

    CHANGE_PAGE: "PATRON/CHANGE_PAGE",
    PATRON_CREATE: "PATRON/CREATE",
  };
  